### ISSUE TITLE
bug: No such file or directory

### ISSUE THREAD

**Issue by MscMin** [10TeamPro/botProject#37]
## Issue: Bug
Error: ENOENT: no such file or directory, open 'rsc/data/dept.txt'

## Description

학과 사무실 정보 적혀있는 파일에서 정보를 읽어오는 과정에서 경로가 이상한 건지 뭐가 문제인 건지 모르겠지만 안 됩니다.

## ToDo
1. 파일 경로 제대로 읽어오는 것만 수행하면 됩니다.
![image](https://user-images.githubusercontent.com/113351941/202899860-f195a627-21f4-4ec0-b606-cb196ace87c8.png)

## ETC
기타사항

## Desktop 환경 
 - Version [e.g. 22]: Node.js v18.12.0

**Comment by tldk42** [comment]
한번 작업중인 폴더 위치 확인 해보시겠어요??

**Comment by MscMin** [comment]
확인해보니까 작업 중인 폴더 위치가 잘못 설정되어 있었네요... 따로 설정 건든 적이 없는데 오늘 갑자기 이러네요.
해결하는 거 도와주셔서 감사합니다!
