### ISSUE TITLE
[BUG] Node.js 환경에서 파이썬 코드 실행시 파일 깨짐 현상

### ISSUE THREAD

**Issue by euny0ung** [10TeamPro/botProject#38]
## Issue: Bug
Node.js 환경에서 파이썬 코드 실행시 파일 깨짐

## Description
파이썬으로 짠 스크래핑 코드를 vscode에서 js와 연결하여 실행하면 결과값이 깨집니다.
검색해보니 vscode의 문제인것 같은데 인코딩 형태를 바꿔도 깨지네요.

## ToDo
- [x] 다른 방법 찾아보기
- [x] 실패시 js로 코드 다시 작성

## Desktop 환경 
 - OS: Window10, VScode
 - Version 1.73.1

**Comment by tldk42** [comment]
파이썬으로 스크래핑을 하시고 나온 결과값만 가져오는건가요?
거기서 나온 결과값에서 텍스트가 깨진다는거죠??

**Comment by tldk42** [comment]
파이썬 코드 실행하실 때
child process
python shell 
둘 중에 뭐 쓰시나요??

**Comment by euny0ung** [comment]
> 파이썬 코드 실행하실 때 child process python shell 둘 중에 뭐 쓰시나요??

child process 사용합니다
