### ISSUE TITLE
[BUG] 테스트 통과시에만 merge하는 기능

### ISSUE THREAD

**Issue by euny0ung** [10TeamPro/botProject#53]
## Issue: Bug
테스트를 통과해야 merge 버튼이 활성화되게 설정했었는데 다시 테스트해야할 것 같습니다.

## Description
squre.js 파일로 테스트 후 merge 버튼이 활성화 안 된것까지 확인했는데 다시보니 충돌때문에 그런거였네요.
현재 충돌 부분은 수정한 상태인데 approve해서 확인을 해봐야할것 같습니다.
![image](https://user-images.githubusercontent.com/56199780/203609901-841f0be3-e600-490f-8fbb-c2966c78abd8.png)

## ToDo
- [ ] approve해서 merge버튼 활성화 확인
- [ ] 오류가 있다면 재설정

## ETC
..

## Desktop 환경 
 - OS: Window
 - Version: 10

**Comment by MscMin** [comment]
오류 내용을 보니까 mocha명령어가 수행이 안 됐는데 main.yml workflow 파일 바꾸고 나서 안 됐네요...
일단 제가 살펴보고 스크립트 수정하고 결과 봐야 할 거 같네요.

**Comment by tldk42** [comment]
기능은 작동합니다.
막아져요

**Comment by MscMin** [comment]
수정했고, PR한 후에 결과보고 이슈해결했는지 아닌지 결정합시다
