### ISSUE TITLE
[Feature] RTM -> bolt

### ISSUE THREAD

**Issue by tldk42** [10TeamPro/botProject#70]
## Issue: Feature & Refactoring
현재 사용하고 있는 rtm api를 bolt로 변경하면 어떨까 합니다.

## Description

- Pros
  - 이제 추가 될 기능들의 메시지 형식이 좀 더 다양하고 길어질 것으로 예상됨
  - slack 레퍼런스에서 rtm은 더 이상 사용 되지 않음 현재  채팅 형 앱으로 밀고있는건  bolt
  - bolt가 rtm에 비해 더 직관적으로 함수를 작성할 수 있음.
  - bolt는 메시지를 attachments, block등 여러 형식으로 보낼 수 있음 (rtm은 string 형식의  text만 가능)
- Cons
  - rtm에 비해 전송 속도가 느림
  - 기존에 있던 bot 클래스와 관련된 코드를 전체 다 바꿔야함.

**Comment by MscMin** [comment]
어차피 교수님께서 성능 측면에서는 크게 안 보실 거 같습니다. 그리고 시간은 좀 느리더라도 저희가 만족할 만한 퀄리티 나오면 더 의미있는  거 같아서 저는 괜찮아보이네요.
