### ISSUE TITLE
[BUG] 봇 응답이 여러 단계시 함수 수정 요망

### ISSUE THREAD

**Issue by tldk42** [10TeamPro/botProject#86]
## Issue: Bug 
함수 반환문 수정 필요

![image](https://user-images.githubusercontent.com/83587015/205751825-50a57ec9-0d32-4546-adf5-e67e8b507a84.png)

**응답없음**
응답레벨 3에서 빠져나오지 못함
이상한 문자 입력시 예외로 안내메시지 전송

## Description
봇이 여러단계를 거쳐서 답을 해야하면 함수 리턴을 
{메시지, 성공여부} 형식으로 작성해주세요.

-----------------------------------
**여기서 채널 응답레벨을 3으로 설정해줍니다.** 
```
case '학과 사무실 안내':
            sendMsg = requestDept;
            this.#channelMap.set(channel, 3);
            break;
```

**응답 레벨이 3이면 성공적으로 반환했는지 확인하고 다시 원래 케이스로 돌아갈지 확인해야합니다.**
```
 case 3: {
        const temp = findOffice(text);
        /** @todo 이부분에 성공했는지 여부 확인 후 성공시 1로 돌아가고 아니면 루프 */
        // sendMsg = temp.success ? temp.msg : 'INPUT ERROR';
        this.#channelMap.set(channel, temp.success ? 1 : 3); <- 이부분
        break;
```

## ToDo
- [ ] findOffice

**Comment by MscMin** [comment]
이러면 지금 대부분의 리턴 값을 수정해야겠네요.. 일단 개인 용무 때문에 당장은 안 되고 끝나고 나서 수정하겠습니다!

**Comment by tldk42** [comment]
> 이러면 지금 대부분의 리턴 값을 수정해야겠네요.. 일단 개인 용무 때문에 당장은 안 되고 끝나고 나서 수정하겠습니다!

기능2번은 되어있고
지금 현재는 4번 리턴문만 수정되면 됩니다
