### ISSUE TITLE
[Feature] levenshtein distance 라이브러리 문제

### ISSUE THREAD

**Issue by euny0ung** [10TeamPro/botProject#90]
## Issue: Feature
levenshtein distance 기능 구현에 문제가 있습니다.

## Description

- 예를 들어 fast와 faster의 거리를 계산해보면 2입니다. 글자수가 맞지 않는 경우 글자수 차이를 거리에 합산하는 것 같습니다.
- 이것 때문에 computer을 입력하면 가장 유사한 학과로 Computer Science and Engineering가 아닌 accounting이 나옵니다. accounting과 computer의 거리를 계산해보면 8입니다. computer과 Computer Science and Engineering의 거리는 24입니다.  이 외에 글자수가 긴 학과들 역시 가장 유사한 학과로 accounting을 출력합니다.
- 현재 fast levenshtein를 쓰고 있는데 다른 라이브러리도 같은 방식으로 거리를 계산해서 라이브러리를 변경해도 해결될 문제가 아닌 것 같습니다.
- 사용자가 computer sceince 이런식으로 풀네임에 가깝게 입력을 해야 정상적으로 출력됩니다.

## ToDo
- [ ] 해결 방안 찾기
- [ ] 코드 수정

## ETC
기타사항

**Comment by tldk42** [comment]
computer만 쳐서 computer science -- 가 나오게 하려면 데이터 가공이 필요해보입니다.
computer science and Engineering에 공백이 4개 있으니 공백 기준으로 분리시키고 비교하면 될거같습니다.
```
 dataInput.forEach((element) => {
    data = element.split('-'); 
    const department = data[0]; // 학과 명 ex) computer science and Engineering
    const parsedDept = department.split(' '); // 공백 제거 [0] [1] [2] [3] 구분
    
```
이 방식으로 parsedDept에 대해 leven을 쓰시고 가장 distance가 적었던 줄에 대해서 답을 하는건 어떨까요?

**Comment by euny0ung** [comment]
해결했습니다 감동적이네요...
